### PR TITLE
V3.0.0

### PR DESCRIPTION
**Pull request by mmmmcoffee**
Update to v3

### CODE REVIEW

**Comment by its-a-feature** [comment]
Can you re-target this to the v3.0.0 branch on this repo? I can then pull that in

**Comment by its-a-feature** [comment]
also, thanks for doing so much work on this! I'm excited to see how things are looking :)

**Comment by mmmmcoffee** [comment]
> Can you re-target this to the v3.0.0 branch on this repo? I can then pull that in

ok think I did it?

**Comment by its-a-feature** [comment]
Still says it's targeting the main branch

**Comment by its-a-feature** [comment]
ohh there's a separate PR for the v3.0.0 branch, gotcha. I'll go ahead and close this one and merge that one

**Pull request closed without merging**
